apiVersion: "\x01apple"
kind: CustomResourceDefinition
metadata: {}
spec:
  "\0\0\tv1beta1": true
  group: seeder.cloud.sap
  names:
    kind: CcloudSeed
    plural: ccloudseeds
    singular: ccloud_sed
  scope: ccloud_sed
  versions: []
