apiVersion: v1
kind: Pod
metadata:
  labels:
    name: storage-pod
  name: storage-pod
spec:
  containers:
  - env:
    - name: SENTRY_DSN
      valueFrom:
        secretKeyRef:
          key: dsn
          name: mysecret
    image: myregistry.storage.local:5000/myprestart
    name: my-container
    ports:
    - containerPort: 8080
      protocol: TCP
