apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: petclinic
    image: mysql
    name: mysql
    ports:
    - containerPort: 3306
      name: mysql
