apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXJodWI6eyJkb2NrZXJodiI6IHsiaDotDotDotDotDotConfig
kind: Secret
metadata:
  name: registry-account-credentials
type: kubernetes.io/dockerconfigjson
